### ISSUE TITLE
CI on circleci - Linux

### ISSUE THREAD

**Issue by AbdealiJK** [atom/ci#32] opened 2016-02-07 15:16 UTC
I was trying to get circleci + atom testing for my package.
I came across this issue when trying to use the yml file given here. The wget to install ato is throwing the error. It says `Unable to establish SSL connection. Action failed: wget -O atom-amd64.deb https://atom.io/download/deb`

Which is very weird because:
 - The link works from a browser
 - The wget command works on my computer
 - The Internet on the circleci instance doesnt seem to have any problem (pip works)

Any clue as to why it fails ? I tried sshing into it - it kept giving the same error. Tried <http://atom.io/download/deb> (http instead of https) also - same error.

https://circleci.com/gh/coala-analyzer/coala-atom/2#tests

**Comment by Arcanemagus** [comment] 2016-02-07 20:22
Duplicate of #28, which has a workaround till CircleCI fixes their containers :wink:.

**Comment by 50Wliu** [comment] 2016-02-07 20:38
Thanks @Arcanemagus!

**Closed by 50Wliu** 2016-02-07 20:38 UTC
